import {
  Award,
  BarChart3,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  ClipboardCheck,
  Cloud,
  Code2,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Eye,
  FileText,
  Fuel,
  Gamepad2,
  Gift,
  GitBranch,
  Glasses,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Network,
  Newspaper,
  Palette,
  PenTool,
  Plane,
  Puzzle,
  Radio,
  Rocket,
  Scale,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TestTube,
  Trophy,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "@/content/types";

const icons: Record<IconName, LucideIcon> = {
  code: Code2,
  smartphone: Smartphone,
  palette: Palette,
  cloud: Cloud,
  shield: ShieldCheck,
  brain: Brain,
  boxes: Boxes,
  gamepad: Gamepad2,
  database: Database,
  rocket: Rocket,
  users: Users,
  globe: Globe,
  layers: Layers,
  workflow: Workflow,
  chart: BarChart3,
  cpu: Cpu,
  lock: Lock,
  zap: Zap,
  sparkles: Sparkles,
  building: Building2,
  health: HeartPulse,
  bank: Landmark,
  cart: ShoppingCart,
  plane: Plane,
  radio: Radio,
  fuel: Fuel,
  education: GraduationCap,
  home: Home,
  store: Store,
  wrench: Wrench,
  settings: Settings,
  target: Target,
  award: Award,
  handshake: Handshake,
  leaf: Leaf,
  scale: Scale,
  lightbulb: Lightbulb,
  message: MessageSquare,
  server: Server,
  git: GitBranch,
  headphones: Headphones,
  card: CreditCard,
  compass: Compass,
  box: Box,
  eye: Eye,
  megaphone: Megaphone,
  book: BookOpen,
  mic: Mic,
  file: FileText,
  news: Newspaper,
  briefcase: Briefcase,
  heart: Heart,
  gift: Gift,
  trophy: Trophy,
  map: MapPin,
  pen: PenTool,
  monitor: Monitor,
  network: Network,
  test: TestTube,
  coins: Coins,
  glasses: Glasses,
  wallet: Wallet,
  clipboard: ClipboardCheck,
  puzzle: Puzzle,
  bot: Bot,
};

interface IconProps {
  name?: IconName;
  className?: string;
  size?: number;
}

export default function Icon({ name, className, size = 28 }: IconProps) {
  const Component = (name && icons[name]) || Sparkles;

  return (
    <Component
      className={className}
      size={size}
      strokeWidth={1.6}
      aria-hidden="true"
    />
  );
}
